package com.supre.Task3_ATM_Interface;

public class UserDetails 
{
	private static int ACCOUNTNUMBER = 101;
	private int accNumber;
	private String userName;
	private double accBalance;
	
	public UserDetails(String userName, double accBalance) {
		super();
		this.userName = userName;
		this.accBalance = accBalance;
		this.accNumber = autoGeneratedaccNumber();
	}

	public  int getAccNumber() {
		return accNumber;
	}

	public void setAccNumber(int accNumber) {
		this.accNumber = accNumber;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public double getAccBalance() {
		return accBalance;
	}

	public void setAccBalance(double accBalance) {
		this.accBalance = accBalance;
	}
	
	private static int autoGeneratedaccNumber()
	{
		return ACCOUNTNUMBER++;
	}

	@Override
	public String toString() {
		return "UserAccountDetails [accNumber="+accNumber+", userName=" + userName + ", accBalance=" + accBalance + "]";
	}
	
	
	
	
	
	
	

}
